data_path: c:/users/uiousername/expipe_temp_storage
processing:
  data_path: /home/user/expipe_temp_storage
  username: <processing server username>
  hostname: user@ipaddress
norstore:
  data_path: /norstore_osl/projects/NS9048K/server
  username: <norstore username>
  hostname: login.norstore.uio.no
firebase:
  email: your@email.com
  password: yourpassword
  config:
    apiKey: AIzaSyAjGqZwiCKS2333m820e9UdZ7jbnkfEpjw
    authDomain: expipe-26506.firebaseapp.com
    databaseURL: https://expipe-26506.firebaseio.com
    storageBucket: expipe-26506.appspot.com
